/**
 * control
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package hu.xlipton.control.model


import com.google.gson.annotations.SerializedName

/**
 * The control data containing the necessary control informations and data
 *
 * @param timeStamp The time the control was sent in UTC (zulu) time
 * @param switch Shows if the switch control is turned on or off.
 * @param slider The number set by the slider control.
 * @param rotaryKnob The number set by the rotary knob control.
 * @param select 
 */

data class ControlData (

    /* The time the control was sent in UTC (zulu) time */
    @SerializedName("timeStamp")
    val timeStamp: java.time.OffsetDateTime? = null,

    /* Shows if the switch control is turned on or off. */
    @SerializedName("switch")
    val switch: kotlin.Boolean? = null,

    /* The number set by the slider control. */
    @SerializedName("slider")
    val slider: java.math.BigDecimal? = null,

    /* The number set by the rotary knob control. */
    @SerializedName("rotaryKnob")
    val rotaryKnob: java.math.BigDecimal? = null,

    @SerializedName("select")
    val select: kotlin.collections.List<kotlin.Boolean>? = null

)

