# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ControlData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time_stamp=None, switch=None, slider=None, rotary_knob=None, select=None):  # noqa: E501
        """ControlData - a model defined in OpenAPI

        :param time_stamp: The time_stamp of this ControlData.  # noqa: E501
        :type time_stamp: datetime
        :param switch: The switch of this ControlData.  # noqa: E501
        :type switch: bool
        :param slider: The slider of this ControlData.  # noqa: E501
        :type slider: float
        :param rotary_knob: The rotary_knob of this ControlData.  # noqa: E501
        :type rotary_knob: float
        :param select: The select of this ControlData.  # noqa: E501
        :type select: List[bool]
        """
        self.openapi_types = {
            'time_stamp': datetime,
            'switch': bool,
            'slider': float,
            'rotary_knob': float,
            'select': List[bool]
        }

        self.attribute_map = {
            'time_stamp': 'timeStamp',
            'switch': 'switch',
            'slider': 'slider',
            'rotary_knob': 'rotaryKnob',
            'select': 'select'
        }

        self._time_stamp = time_stamp
        self._switch = switch
        self._slider = slider
        self._rotary_knob = rotary_knob
        self._select = select

    @classmethod
    def from_dict(cls, dikt) -> 'ControlData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ControlData of this ControlData.  # noqa: E501
        :rtype: ControlData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_stamp(self):
        """Gets the time_stamp of this ControlData.

        The time the control was sent in UTC (zulu) time  # noqa: E501

        :return: The time_stamp of this ControlData.
        :rtype: datetime
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this ControlData.

        The time the control was sent in UTC (zulu) time  # noqa: E501

        :param time_stamp: The time_stamp of this ControlData.
        :type time_stamp: datetime
        """

        self._time_stamp = time_stamp

    @property
    def switch(self):
        """Gets the switch of this ControlData.

        Shows if the switch control is turned on or off.  # noqa: E501

        :return: The switch of this ControlData.
        :rtype: bool
        """
        return self._switch

    @switch.setter
    def switch(self, switch):
        """Sets the switch of this ControlData.

        Shows if the switch control is turned on or off.  # noqa: E501

        :param switch: The switch of this ControlData.
        :type switch: bool
        """

        self._switch = switch

    @property
    def slider(self):
        """Gets the slider of this ControlData.

        The number set by the slider control.  # noqa: E501

        :return: The slider of this ControlData.
        :rtype: float
        """
        return self._slider

    @slider.setter
    def slider(self, slider):
        """Sets the slider of this ControlData.

        The number set by the slider control.  # noqa: E501

        :param slider: The slider of this ControlData.
        :type slider: float
        """

        self._slider = slider

    @property
    def rotary_knob(self):
        """Gets the rotary_knob of this ControlData.

        The number set by the rotary knob control.  # noqa: E501

        :return: The rotary_knob of this ControlData.
        :rtype: float
        """
        return self._rotary_knob

    @rotary_knob.setter
    def rotary_knob(self, rotary_knob):
        """Sets the rotary_knob of this ControlData.

        The number set by the rotary knob control.  # noqa: E501

        :param rotary_knob: The rotary_knob of this ControlData.
        :type rotary_knob: float
        """

        self._rotary_knob = rotary_knob

    @property
    def select(self):
        """Gets the select of this ControlData.


        :return: The select of this ControlData.
        :rtype: List[bool]
        """
        return self._select

    @select.setter
    def select(self, select):
        """Sets the select of this ControlData.


        :param select: The select of this ControlData.
        :type select: List[bool]
        """
        if select is not None and len(select) > 4:
            raise ValueError("Invalid value for `select`, number of items must be less than or equal to `4`")  # noqa: E501
        if select is not None and len(select) < 4:
            raise ValueError("Invalid value for `select`, number of items must be greater than or equal to `4`")  # noqa: E501

        self._select = select
