# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class ControlData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ControlData - a model defined in OpenAPI

        time_stamp: The time_stamp of this ControlData [Optional].
        switch: The switch of this ControlData [Optional].
        slider: The slider of this ControlData [Optional].
        rotary_knob: The rotary_knob of this ControlData [Optional].
        select: The select of this ControlData [Optional].
    """

    time_stamp: Optional[datetime] = None
    switch: Optional[bool] = None
    slider: Optional[float] = None
    rotary_knob: Optional[float] = None
    select: Optional[List[bool]] = None

ControlData.update_forward_refs()
