#:kivy 1.0
MainScreen:

#:set background (30/255, 43/255, 51/255, 1)
#:set accent (1, 110/255, 64/255, 1)

<MainScreen>: 
    orientation: "vertical"
    RelativeLayout:
        canvas.before:
            Color:
                rgba: 1, 110/255, 64/255, 1
            Rectangle:
                size: self.size
        size_hint: 1, 0.4
        Label:
            text: "GDevice"
            color: 30/255, 43/255, 51/255, 1
    Button:
        text: "Start Server"
        on_press: root.on_server_button_click()  
    Label:
        text: root.switch_value
        color: 1, 110/255, 64/255, 1
        background_color: 30/255, 43/255, 51/255, 1
        canvas.before:
            Color:
                rgba: self.background_color
            Rectangle:
                size: self.size
                pos: self.pos
    Label:
        text: "Label1"
        color: 1, 110/255, 64/255, 1
        background_color: 30/255, 43/255, 51/255, 1
        canvas.before:
            Color:
                rgba: self.background_color
            Rectangle:
                size: self.size
                pos: self.pos
    Label:
        text: "Label1"
        color: 1, 110/255, 64/255, 1
        background_color: 30/255, 43/255, 51/255, 1
        canvas.before:
            Color:
                rgba: self.background_color
            Rectangle:
                size: self.size
                pos: self.pos            
    Label:
        text: "Label1"
        color: 1, 110/255, 64/255, 1
        background_color: 30/255, 43/255, 51/255, 1
        canvas.before:
            Color:
                rgba: self.background_color
            Rectangle:
                size: self.size
                pos: self.pos
