import multiprocessing
import uvicorn
from GDevice.gserver.openapi_server.models.control_data import ControlData
from fastapi import FastAPI
from typing import Dict, List  # noqa: F401
from fastapi import (  # noqa: F401
    APIRouter,
    Body,
    Cookie,
    Depends,
    Form,
    Header,
    Path,
    Query,
    Response,
    Security,
    status,
)
from GDevice.gserver.openapi_server.models.extra_models import TokenModel  # noqa: F401
from GDevice.gserver.openapi_server.models.control_data import ControlData

def run_server(server_conn: multiprocessing.Pipe):
    
    router = APIRouter()

    @router.post(
        "/control",
        responses={
            204: {"description": "The sent control was succesfuly processed."},
            400: {"description": "Invalid imput."},
            500: {"description": "Internal server error."},
        },
        tags=["default"],
    )
    async def control_post(
        control_data: ControlData = Body(None, description=""),
    ) -> None:
        """This operation allows for sending control data."""
        server_conn.send(control_data)
    
    app = FastAPI(
        title="control",
        description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
        version="1.0",
    )

    app.include_router(router)

    uvicorn.run(app=app, host='0.0.0.0', port=8000, log_level="info")
       
def start_server(child_conn: multiprocessing.Pipe):
    global server_proc
    server_proc = multiprocessing.Process(target=run_server, args=(child_conn,), daemon=True)
    server_proc.start()

def stop_server(): 
    server_proc.terminate()

if __name__ == '__main__':
    multiprocessing.freeze_support()
    from kivy.app import App
    from kivy.uix.widget import Widget
    from kivy.uix.boxlayout import BoxLayout
    from kivy.uix.stacklayout import StackLayout
    from kivy.properties import StringProperty
    from kivy.properties import BooleanProperty
    from kivy.clock import Clock

    class GDevice(App):
        pass
    class MainScreen(BoxLayout):
        server_button = StringProperty("Start server")
        is_server_up = BooleanProperty(False)

        switch_value = StringProperty("N/A")
        slider_value = StringProperty("N/A")
        rotary_knob_value = StringProperty("N/A")
        select_value = StringProperty("N/A")

        ui_conn, server_conn = multiprocessing.Pipe()

        def on_server_button_click(self):
            print("clicked")
            if (self.is_server_up):
                stop_server()
                self.is_server_up = False
                self.server_button = "Start Server"
            else:
                self.start_update()
                self.is_server_up = True
                self.server_button = "Stop Server"
                start_server(self.server_conn)


        def start_update(self):
            Clock.schedule_interval(self.update_ui, 1)

        def update_ui(self, dt):
            if self.ui_conn.poll():
                control: ControlData = self.ui_conn.recv()
                if control.switch:
                    self.switch_value = 'ON'
                else:
                    self.switch_value = 'OFF'
                self.slider_value = str(control.slider)
                self.rotary_knob_value = str(control.rotary_knob)
                self.select_value = str(control.select)


    GDevice().run()